### ISSUE TITLE
[libdpdk] Cannot Use with Non-Mellanox NIC

### ISSUE THREAD

**Issue by YifanJiangPolyU** [demikernel/dpdk-rs#1]
I try to use this wrapper with non-Mellanox NIC but it doesn't work.

I ran the following command (EAL args are for my machine): 
```
./target/debug/init -c3 -n4
```
 and got the following output:
```
EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: No legacy callbacks, legacy socket not created
thread 'main' panicked at 'assertion failed: nb_ports > 0', src/bin/init.rs:24:9
```

Apparently, it does not detect any NIC device. On my machine, I have properly configured the NIC for DPDK (tested using my old/working DPDK application).

I'm using the default feature (mlx4) because `load_mlx_driver` does not do anything for mlx4.

I also tried linking statically (identical link targets to my old/working DPDK application written in C), but it does not help.

Any advice on how to port this to non-Mellanox NIC would be really helpful.

**Comment by YifanJiangPolyU** [comment]
Turned out the PMD shared library is not loaded properly. I had to use `-d` cmd line option to add the PMD shared library I want to use. The final result looks like this:
```
./target/debug/init -c3 -n4 --proc-type=auto -d /usr/local/lib/x86_64-linux-gnu/librte_net_igc.so.21
```
Not sure why static linking didn't work.

**Comment by ppenna** [comment]
@YifanJiangPolyU may I go on and close this?
